routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginOrRegister')->name('loginRedirect');

Auth::routes(['verify' => true]);

Route::get('/invitations/accept/{key}', 'Auth\InvitationController@show')->name('invitations.accept');
Route::post('/invitations/accept/{key}', 'Auth\InvitationController@store')->name('invitations.send');

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/auth/login-recovery', 'Auth\RecoveryLoginController@get')->name('recovery.login');
    Route::post('/auth/login-recovery', 'Auth\RecoveryLoginController@store');
});

Route::middleware(['auth', '2fa'])->group(function () {
    Route::post('/validate2fa', 'Auth\Validate2faController@index')->name('validate2fa');
});

Route::middleware(['auth', 'verified', 'mfa'])->group(function () {
    Route::name('dashboard.')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::get('/dashboard/calls', 'DashboardController@calls');
        Route::get('/dashboard/notes', 'DashboardController@notes');
        Route::get('/dashboard/debts', 'DashboardController@debts');
        Route::post('/dashboard/setTab', 'DashboardController@setTab');
    });

    Route::get('/compliance', 'ComplianceController@index')->name('compliance');
    Route::post('/compliance/sign', 'ComplianceController@store');
    Route::get('/changelog', 'ChangelogController@index')->name('changelog.index');

    Route::get('/emotions', 'EmotionController@primaries');
    Route::get('/emotions/primaries/{emotion}/secondaries', 'EmotionController@secondaries');
    Route::get('/emotions/primaries/{emotion}/secondaries/{secondaryEmotion}/emotions', 'EmotionController@emotions');

    Route::name('people.')->group(function () {
        Route::get('/people/notfound', 'ContactsController@missing')->name('missing');
        Route::get('/people/archived', 'ContactsController@archived')->name('archived');

        // Dashboard
        Route::get('/people', 'ContactsController@index')->name('index');
        Route::get('/people/add', 'ContactsController@create')->name('create');
        Route::get('/people/list', 'ContactsController@list')->name('list');
        Route::post('/people', 'ContactsController@store')->name('store');
        Route::get('/people/{contact}', 'ContactsController@show')->name('show');
        Route::get('/people/{contact}/edit', 'ContactsController@edit')->name('edit');
        Route::put('/people/{contact}', 'ContactsController@update')->name('update');
        Route::delete('/people/{contact}', 'ContactsController@destroy')->name('destroy');

        // Avatar
        Route::get('/people/{contact}/avatar', 'Contacts\\AvatarController@edit')->name('avatar.edit');
        Route::post('/people/{contact}/avatar', 'Contacts\\AvatarController@update')->name('avatar.update');
        Route::post('/people/{contact}/makeProfilePicture/{photo}', 'Contacts\\AvatarController@photo')->name('avatar.photo');

        // Life events
        Route::name('lifeevent.')->group(function () {
            Route::get('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@index')->name('index');
            Route::get('/lifeevents/categories', 'Contacts\\LifeEventsController@categories')->name('categories');
            Route::get('/lifeevents/categories/{lifeEventCategory}/types', 'Contacts\\LifeEventsController@types')->name('types');
            Route::post('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@store')->name('store');
            Route::delete('/lifeevents/{lifeEvent}', 'Contacts\\LifeEventsController@destroy')->name('destroy');
        });

        // Contact information
        Route::get('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@getContactFields');
        Route::post('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@storeContactField');
        Route::put('/people/{contact}/contactfield/{contactField}', 'Contacts\\ContactFieldsController@editContactField');
        Route::delete('/people/{contact}/contactfield/{contactField}', 'Contacts\\ContactFieldsController@destroyContactField');
        Route::get('/people/{contact}/contactfieldtypes', 'Contacts\\ContactFieldsController@getContactFieldTypes');

        // Export as vCard
        Route::get('/people/{contact}/vcard', 'ContactsController@vcard')->name('vcard');

        // Addresses
        Route::get('/countries', 'Contacts\\AddressesController@getCountries');
        Route::get('/people/{contact}/addresses', 'Contacts\\AddressesController@index');
        Route::post('/people/{contact}/addresses', 'Contacts\\AddressesController@store');
        Route::put('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@edit');
        Route::delete('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@destroy');

        // Work information
        Route::name('work.')->group(function () {
            Route::get('/people/{contact}/work/edit', 'ContactsController@editWork')->name('edit');
            Route::post('/people/{contact}/work/update', 'ContactsController@updateWork')->name('update');
        });

        // Introductions
        Route::name('introductions.')->group(function () {
            Route::get('/people/{contact}/introductions/edit', 'Contacts\\IntroductionsController@edit')->name('edit');
            Route::post('/people/{contact}/introductions/update', 'Contacts\\IntroductionsController@update')->name('update');
        });

        // Tags
        Route::name('tags.')->group(function () {
            Route::get('/tags', 'Contacts\\TagsController@index')->name('index');
            Route::get('/people/{contact}/tags', 'Contacts\\TagsController@get')->name('get');
            Route::post('/people/{contact}/tags/update', 'Contacts\\TagsController@update')->name('update');
        });

        // Notes
        Route::resource('people/{contact}/notes', 'Contacts\\NotesController')->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::post('/people/{contact}/notes/{note}/toggle', 'Contacts\\NotesController@toggle');

        // Food preferences
        Route::name('food.')->group(function () {
            Route::get('/people/{contact}/food', 'ContactsController@editFoodPreferences')->name('index');
            Route::post('/people/{contact}/food/save', 'ContactsController@updateFoodPreferences')->name('update');
        });

        // Relationships
        Route::resource('people/{contact}/relationships', 'Contacts\\RelationshipsController')->only([
            'create', 'store', 'edit', 'update', 'destroy',
        ]);

        // Pets
        Route::resource('people/{contact}/pets', 'Contacts\\PetsController')->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::get('/petcategories', 'Contacts\\PetsController@getPetCategories');

        // Reminders
        Route::resource('people/{contact}/reminders', 'Contacts\\RemindersController')->except(['index', 'show']);

        // Tasks
        Route::resource('people/{contact}/tasks', 'Contacts\\TasksController')->only([
            'index',
        ]);
        Route::resource('tasks', 'TasksController')->only([
            'index', 'store', 'update', 'destroy',
        ]);

        // Debt
        Route::resource('people/{contact}/debts', 'Contacts\\DebtController')->except(['index', 'show']);

        // Phone calls
        Route::resource('people/{contact}/calls', 'Contacts\\CallsController')->except(['show']);

        // Conversations
        Route::resource('people/{contact}/conversations', 'Contacts\\ConversationsController')->except(['show']);

        // Documents
        Route::resource('people/{contact}/documents', 'Contacts\\DocumentsController')->only(['index', 'store', 'destroy']);

        // Photos
        Route::resource('people/{contact}/photos', 'Contacts\\PhotosController')->only(['index', 'store', 'destroy']);

        // Search
        Route::post('/people/search', 'ContactsController@search')->name('search');

        // Stay in touch information
        Route::post('/people/{contact}/stayintouch', 'ContactsController@stayInTouch');

        // Set favorite
        Route::post('/people/{contact}/favorite', 'ContactsController@favorite');

        // Archive/Unarchive
        Route::put('/people/{contact}/archive', 'ContactsController@archive');

        // Activities
        Route::get('/activityCategories', 'Contacts\\ActivitiesController@categories')->name('activities.categories');
        Route::resource('people/{contact}/activities', 'Contacts\\ActivitiesController')->only(['index']);
        Route::get('/people/{contact}/activities/contacts', 'Contacts\\ActivitiesController@contacts')->name('activities.contacts');
        Route::get('/people/{contact}/activities/summary', 'Contacts\\ActivitiesController@summary')->name('activities.summary');
        Route::get('/people/{contact}/activities/{year}', 'Contacts\\ActivitiesController@year')->name('activities.year');

        // Audit logs
        Route::get('/people/{contact}/auditlogs', 'Contacts\\ContactAuditLogController@index')->name('auditlogs');
    });

    Route::name('journal.')->group(function () {
        Route::get('/journal', 'JournalController@index')->name('index');
        Route::get('/journal/entries', 'JournalController@list')->name('list');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\User\User;
use App\Helpers\DateHelper;
use App\Models\Contact\Debt;
use Illuminate\Http\Request;
use App\Helpers\AccountHelper;
use function Safe\json_encode;
use App\Helpers\InstanceHelper;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\Debt\Debt as DebtResource;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View|\Illuminate\Contracts\View\Factory
     */
    public function index()
    {
        $account = auth()->user()->account()
            ->withCount(
                'contacts', 'reminders', 'notes', 'activities', 'gifts', 'tasks'
            )->with('debts.contact')
            ->first();

        $numberOfContacts = $account->contacts()
                                    ->real()
                                    ->active()
                                    ->count();

        if ($numberOfContacts === 0) {
            return view('dashboard.blank');
        }

        // Fetch last updated contacts
        $lastUpdatedContactsCollection = collect([]);
        $lastUpdatedContacts = $account->contacts()
            ->real()
            ->active()
            ->alive()
            ->latest('last_consulted_at')
            ->limit(10)
            ->get();
        foreach ($lastUpdatedContacts as $contact) {
            $data = [
                'id' => $contact->hashID(),
                'has_avatar' => $contact->has_avatar,
                'avatar_url' => $contact->getAvatarURL(),
                'initials' => $contact->getInitials(),
                'default_avatar_color' => $contact->default_avatar_color,
                'complete_name' => $contact->name,
            ];
            $lastUpdatedContactsCollection->push(json_encode($data));
        }

        $debts = $account->debts()->inProgress();

        $debt_due = $debts->due()->get()
            ->reduce(function ($totalDueDebt, Debt $debt) {
                return $totalDueDebt + $debt->amount;
            }, 0);

        $debt_owed = $debts->owed()->get()
            ->reduce(function ($totalOwedDebt, Debt $debt) {
                return $totalOwedDebt + $debt->amount;
            }, 0);

        // get last 3 changelog entries
        $changelogs = InstanceHelper::getChangelogEntries(3);

        // Load the reminderOutboxes for the upcoming three months
        $reminderOutboxes = [
            0 => AccountHelper::getUpcomingRemindersForMonth(auth()->user()->account, 0),
            1 => AccountHelper::getUpcomingRemindersForMonth(auth()->user()->account, 1),
            2 => AccountHelper::getUpcomingRemindersForMonth(auth()->user()->account, 2),
        ];

        $data = [
            'lastUpdatedContacts' => $lastUpdatedContactsCollection,
            'number_of_contacts' => $numberOfContacts,
            'number_of_reminders' => $account->reminders_count,
            'number_of_notes' => $account->notes_count,
            'number_of_activities' => $account->activities_count,
            'number_of_gifts' => $account->gifts_count,
            'number_of_tasks' => $account->tasks_count,
            'debt_due' => $debt_due,
            'debt_owed' => $debt_owed,
            'debts' => $debts,
            'user' => auth()->user(),
            'changelogs' => $changelogs,
            'reminderOutboxes' => $reminderOutboxes,
        ];

        return view('dashboard.index', $data);
    }

    /**
     * Get calls for the dashboard.
     * @return Collection
     */
    public function calls()
    {
        $callsCollection = collect([]);
        $calls = auth()->user()->account->calls()
            ->get()
            ->reject(function ($call) {
                return is_null($call->contact);
            })
            ->take(15);

        foreach ($calls as $call) {
            $data = [
                'id' => $call->id,
                'called_at' => DateHelper::getShortDate($call->called_at),
                'name' => $call->contact->getIncompleteName(),
                'contact_id' => $call->contact->hashID(),
            ];
            $callsCollection->push($data);
        }

        return $callsCollection;
    }

    /**
     * Get notes for the dashboard.
     * @return Collection
     */
    public function notes()
    {
        $notesCollection = collect([]);
        $notes = auth()->user()->account->notes()->favorited()->get();

        foreach ($notes as $note) {
            $data = [
                'id' => $note->id,
                'body' => $note->body,
                'created_at' => DateHelper::getShortDate($note->created_at),
                'name' => $note->contact->getIncompleteName(),
                'contact' => [
                    'id' => $note->contact->hashID(),
                    'has_avatar' => $note->contact->has_avatar,
                    'avatar_url' => $note->contact->getAvatarURL(),
                    'initials' => $note->contact->getInitials(),
                    'default_avatar_color' => $note->contact->default_avatar_color,
                    'complete_name' => $note->contact->name,
                ],
            ];
            $notesCollection->push($data);
        }

        return $notesCollection;
    }

    /**
     * Get debts for the dashboard.
     * @return Collection
     */
    public function debts()
    {
        $debtsCollection = collect([]);
        $debts = auth()->user()->account->debts()->get();

        foreach ($debts as $debt) {
            $debtsCollection->push(new DebtResource($debt));
        }

        return $debtsCollection;
    }

    /**
     * Save the current active tab to the User table.
     */
    public function setTab(Request $request)
    {
        auth()->user()->dashboard_active_tab = $request->input('tab');
        auth()->user()->save();
    }
}

resources/views/dashboard/_monthReminder.blade.php
@foreach($reminderOutboxesList as $month => $reminderOutboxes)
    <h3 class="ttu fw5 f5 pb2">{{ \App\Helpers\DateHelper::getMonthAndYear($month) }}</h3>
    <ul class="mb4">
        @if(count($reminderOutboxes) > 0)
            @foreach($reminderOutboxes as $reminderOutbox)
            @if (!is_object($reminderOutbox->reminder))
                @continue;
            @endif
            <li class="pb2">
                <span class="ttu f6 mr2 black-60">{{ \App\Helpers\DateHelper::getShortDateWithoutYear($reminderOutbox->planned_date) }}</span>
                <span>
                    @if ($reminderOutbox->reminder->contact->is_partial)

                        @php($relatedRealContact = $reminderOutbox->reminder->contact->getRelatedRealContact())
                        <a href="{{ route('people.show', $relatedRealContact) }}">{{ $relatedRealContact->getIncompleteName() }}</a>

                    @else

                        <a href="{{ route('people.show', $reminderOutbox->reminder->contact) }}">{{ $reminderOutbox->reminder->contact->getIncompleteName() }}</a>

                    @endif
                </span>
                {{ $reminderOutbox->reminder->title }}
            </li>
            @endforeach
        @else
            <p>{{ trans('dashboard.reminders_none') }}</p>
        @endif
    </ul>
@endforeach

resources/views/dashboard/blank.blade.php
@extends('layouts.skeleton')

@section('content')

  <div class="mw6 center mt5 mt6-ns mb4 ph3 ph0-ns">
    <div class="tc mb5">
      <img src="img/dashboard/blank.svg">
    </div>
    <h2 class="f2 mb4 normal tc lh-title">{{ trans('dashboard.dashboard_blank_title') }}</h2>
    <p class="tc f4 mb4">{{ trans('dashboard.dashboard_blank_description') }}</p>
    <p class="tc mb5"><a href="{{ route('people.create') }}" id="button-add-contact" class="btn btn-primary pa4 f4">{{ trans('dashboard.dashboard_blank_cta') }}</a></p>
  </div>

@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="dashboard">

    <section class="ph3 ph5-ns pv4 cf w-100 bg-gray-monica">
      <div class="mw9 center">
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-70-ns ph2">
          <div class="pb2 tc dn-ns w-100">
            {{ trans('people.people_list_last_updated') }}
          </div>
          <div class="h3 overflow-hidden mb2">
            <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} pr2 dn dib-ns v-mid h3" style="line-height: 4rem;">
              {{ trans('people.people_list_last_updated') }}
            </div>
            @foreach($lastUpdatedContacts as $contact)
            <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} pr2 pointer">
              <avatar :contact="{{ $contact }}" :clickable="true"></avatar>
            </div>
            @endforeach
          </div>
        </div>
        <div class="{{ htmldir() == 'ltr' ? 'fl-ns tr' : 'fr-ns tl' }} w-30-ns ph2">
          <a href="{{ route('people.create') }}" class="btn btn-primary w-100 w-auto-ns tc" style="padding: 15px 45px;">
            {{ trans('people.people_list_blank_cta') }}
          </a>
        </div>
      </div>
    </section>

    {{-- Main section --}}
    <section class="ph3 ph5-ns cf w-100 bg-gray-monica">
      <div class="mw9 center">
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-50-ns w-100 pa2">
          <div class="br3 ba b--gray-monica bg-white mb4">
            <div class="pa3 bb b--gray-monica">
              <p class="mb0">
                📅
                {{ trans('dashboard.reminders_next_months') }}
              </p>
            </div>
            <div class="pt3 pr3 pl3 mb4">
              @include('dashboard._monthReminder', ['reminderOutboxesList' => $reminderOutboxes])
            </div>
          </div>
        </div>
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-50-ns w-100 pa2">
          <div class="br3 ba b--gray-monica bg-white mb3">
            <div class="pa3 bb b--gray-monica">
              <p class="mb1 b">☀️ {{ trans('dashboard.product_changes') }} <span class="fr normal"><a href="changelog">{{ trans('dashboard.product_view_details') }}</a></span></p>
              <ul>
                @foreach ($changelogs as $changelog)
                <li class="mb1">
                  <span class="gray f6">{{ $changelog['date'] }}</span>
                  <span class="stat-description">{{ $changelog['title'] }}</span>
                </li>
                @endforeach
              </ul>
            </div>
          </div>

          <dashboard-log :default-active-tab="'{!! auth()->user()->dashboard_active_tab !!}'"></dashboard-log>

          <div class="br3 ba b--gray-monica bg-white mb3">
            <div class="pa3 bb b--gray-monica tc">
              <ul>
                <li class="tc dib fl w-third">
                  <span class="db f3 fw5 green">{{ $number_of_contacts }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_contacts') }}</span>
                </li>
                <li class="tc dib fl w-third">
                  <span class="db f3 fw5 blue">{{ $number_of_activities }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_activities') }}</span>
                </li>
                <li class="tc dib w-third">
                  <span class="db f3 fw5 orange">{{ $number_of_gifts }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_gifts') }}</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
@endsection