routes/web.php
        ]);
        Route::get('/petcategories', 'Contacts\\PetsController@getPetCategories');

        // Reminders
        Route::resource('people/{contact}/reminders', 'Contacts\\RemindersController')->except(['index', 'show']);

        // Tasks
        Route::resource('people/{contact}/tasks', 'Contacts\\TasksController')->only([
            'index',
        ]);
        Route::resource('tasks', 'TasksController')->only([
            'index', 'store', 'update', 'destroy',
        ]);

        // Debt
        Route::resource('people/{contact}/debts', 'Contacts\\DebtController')->except(['index', 'show']);

        // Phone calls
        Route::resource('people/{contact}/calls', 'Contacts\\CallsController')->except(['show']);

        // Conversations
        Route::resource('people/{contact}/conversations', 'Contacts\\ConversationsController')->except(['show']);

        // Documents
        Route::resource('people/{contact}/documents', 'Contacts\\DocumentsController')->only(['index', 'store', 'destroy']);

        // Photos
        Route::resource('people/{contact}/photos', 'Contacts\\PhotosController')->only(['index', 'store', 'destroy']);

        // Search
        Route::post('/people/search', 'ContactsController@search')->name('search');

        // Stay in touch information
        Route::post('/people/{contact}/stayintouch', 'ContactsController@stayInTouch');

        // Set favorite
        Route::post('/people/{contact}/favorite', 'ContactsController@favorite');

        // Archive/Unarchive
        Route::put('/people/{contact}/archive', 'ContactsController@archive');

        // Activities
        Route::get('/activityCategories', 'Contacts\\ActivitiesController@categories')->name('activities.categories');
        Route::resource('people/{contact}/activities', 'Contacts\\ActivitiesController')->only(['index']);
        Route::get('/people/{contact}/activities/contacts', 'Contacts\\ActivitiesController@contacts')->name('activities.contacts');
        Route::get('/people/{contact}/activities/summary', 'Contacts\\ActivitiesController@summary')->name('activities.summary');
        Route::get('/people/{contact}/activities/{year}', 'Contacts\\ActivitiesController@year')->name('activities.year');

        // Audit logs
        Route::get('/people/{contact}/auditlogs', 'Contacts\\ContactAuditLogController@index')->name('auditlogs');
    });

    Route::name('journal.')->group(function () {
        Route::get('/journal', 'JournalController@index')->name('index');
        Route::get('/journal/entries', 'JournalController@list')->name('list');
        Route::get('/journal/entries/{journalEntry}', 'JournalController@get');
        Route::get('/journal/hasRated', 'JournalController@hasRated');
        Route::post('/journal/day', 'JournalController@storeDay');
        Route::delete('/journal/day/{day}', 'JournalController@trashDay');

        Route::get('/journal/add', 'JournalController@create')->name('create');
        Route::post('/journal/create', 'JournalController@save')->name('save');
        Route::get('/journal/entries/{entry}/edit', 'JournalController@edit')->name('edit');
        Route::put('/journal/entries/{entry}', 'JournalController@update')->name('update');
        Route::delete('/journal/{entry}', 'JournalController@deleteEntry');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', 'SettingsController@index')->name('index');
        Route::post('/settings/delete', 'SettingsController@delete')->name('delete');
        Route::post('/settings/reset', 'SettingsController@reset')->name('reset');
        Route::post('/settings/save', 'SettingsController@save')->name('save');

        Route::name('personalization.')->group(function () {
            Route::get('/settings/personalization', 'Settings\\PersonalizationController@index')->name('index');
            Route::get('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@getContactFieldTypes');
            Route::post('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@storeContactFieldType');
            Route::put('/settings/personalization/contactfieldtypes/{contactFieldType}', 'Settings\\PersonalizationController@editContactFieldType');
            Route::delete('/settings/personalization/contactfieldtypes/{contactFieldType}', 'Settings\\PersonalizationController@destroyContactFieldType');

            Route::apiResource('settings/personalization/genders', 'Settings\\GendersController');
            Route::delete('/settings/personalization/genders/{gender}/replaceby/{genderToReplaceWith}', 'Settings\\GendersController@destroyAndReplaceGender');
            Route::get('/settings/personalization/genderTypes', 'Settings\\GendersController@types');
            Route::put('/settings/personalization/genders/default/{gender}', 'Settings\\GendersController@updateDefault');

            Route::get('/settings/personalization/reminderrules', 'Settings\\ReminderRulesController@index');
            Route::post('/settings/personalization/reminderrules/{reminderRule}', 'Settings\\ReminderRulesController@toggle');

            Route::get('/settings/personalization/modules', 'Settings\\ModulesController@index');
            Route::post('/settings/personalization/modules/{module}', 'Settings\\ModulesController@toggle');

            Route::apiResource('settings/personalization/activitytypecategories', 'Account\\Activity\\ActivityTypeCategoriesController');
            Route::apiResource('settings/personalization/activitytypes', 'Account\\Activity\\ActivityTypesController', ['except' => ['index']]);
        });

        Route::get('/settings/export', 'SettingsController@export')->name('export');
        Route::get('/settings/exportToSql', 'SettingsController@exportToSQL')->name('sql');
        Route::get('/settings/import', 'SettingsController@import')->name('import');
        Route::get('/settings/import/report/{importjobid}', 'SettingsController@report')->name('report');
        Route::get('/settings/import/upload', 'SettingsController@upload')->name('upload');
        Route::post('/settings/import/storeImport', 'SettingsController@storeImport')->name('storeImport');

        Route::name('users.')->group(function () {
            Route::get('/settings/users', 'SettingsController@users')->name('index');
            Route::get('/settings/users/create', 'SettingsController@addUser')->name('create');
            Route::post('/settings/users', 'SettingsController@inviteUser')->name('store');
            Route::delete('/settings/users/{user}', 'SettingsController@deleteAdditionalUser')->name('destroy');
            Route::delete('/settings/users/invitations/{invitation}', 'SettingsController@destroyInvitation')->name('invitation.delete');
        });

        Route::name('storage.')->group(function () {
            Route::get('/settings/storage', 'Settings\\StorageController@index')->name('index');
        });

        Route::name('subscriptions.')->group(function () {
            Route::get('/settings/subscriptions', 'Settings\\SubscriptionsController@index')->name('index');
            Route::get('/settings/subscriptions/upgrade', 'Settings\\SubscriptionsController@upgrade')->name('upgrade');
            Route::get('/settings/subscriptions/upgrade/success', 'Settings\\SubscriptionsController@upgradeSuccess')->name('upgrade.success');
            Route::get('/settings/subscriptions/confirmPayment/{id}', 'Settings\\SubscriptionsController@confirmPayment')->name('confirm');
            Route::post('/settings/subscriptions/processPayment', 'Settings\\SubscriptionsController@processPayment')->name('payment');
            Route::get('/settings/subscriptions/invoice/{invoice}', 'Settings\\SubscriptionsController@downloadInvoice')->name('invoice');
            Route::get('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@downgrade')->name('downgrade');
            Route::post('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@processDowngrade');
            Route::get('/settings/subscriptions/archive', 'Settings\\SubscriptionsController@archive')->name('archive');
            Route::post('/settings/subscriptions/archive', 'Settings\\SubscriptionsController@processArchive');
            Route::get('/settings/subscriptions/downgrade/success', 'Settings\\SubscriptionsController@downgradeSuccess')->name('downgrade.success');
            if (! App::environment('production')) {
                Route::get('/settings/subscriptions/forceCompletePaymentOnTesting', 'Settings\\SubscriptionsController@forceCompletePaymentOnTesting')->name('forceCompletePaymentOnTesting');
            }
        });

        Route::get('/settings/auditlogs', 'Settings\\AuditLogController@index')->name('auditlog.index');

        Route::name('tags.')->group(function () {
            Route::get('/settings/tags', 'SettingsController@tags')->name('index');
            Route::get('/settings/tags/add', 'SettingsController@addUser')->name('add');
            Route::delete('/settings/tags/{tag}', 'SettingsController@deleteTag')->name('delete');
        });

        Route::get('/settings/api', 'SettingsController@api')->name('api');
        Route::get('/settings/dav', 'SettingsController@dav')->name('dav');

        Route::post('/settings/updateDefaultProfileView', 'SettingsController@updateDefaultProfileView');

        // Security
        Route::name('security.')->group(function () {
            Route::get('/settings/security', 'SettingsController@security')->name('index');
            Route::post('/settings/security/passwordChange', 'Auth\\PasswordChangeController@passwordChange')->name('passwordChange');
            Route::get('/settings/security/2fa-enable', 'Settings\\MultiFAController@enableTwoFactor')->name('2fa-enable');
            Route::post('/settings/security/2fa-enable', 'Settings\\MultiFAController@validateTwoFactor');

app/Models/Settings/Currency.php
<?php

namespace App\Models\Settings;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    protected $table = 'currencies';

    public $timestamps = false;
}

app/Models/Settings/Term.php
<?php

namespace App\Models\Settings;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Model;

class Term extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * Get the user record associated with the term.
     */
    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('user_id')->withTimestamps();
    }
}

app/Http/Controllers/Api/Settings/ApiAuditLogController.php
<?php

namespace App\Http\Controllers\Api\Settings;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Database\QueryException;
use App\Http\Controllers\Api\ApiController;
use App\Http\Resources\AuditLog\AuditLog as AuditLogResource;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class ApiAuditLogController extends ApiController
{
    /**
     * Get the list of the audit logs.
     *
     * @param Request $request
     * @return JsonResponse|AnonymousResourceCollection
     */
    public function index(Request $request)
    {
        try {
            $logs = auth()->user()->account->auditLogs()
                ->paginate($this->getLimitPerPage());
        } catch (QueryException $e) {
            return $this->respondInvalidQuery();
        }

        return AuditLogResource::collection($logs);
    }
}

app/Http/Controllers/Api/Settings/ApiComplianceController.php
<?php

namespace App\Http\Controllers\Api\Settings;

use Illuminate\Http\Request;
use App\Models\Settings\Term;
use App\Http\Controllers\Api\ApiController;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Http\Resources\Settings\Compliance\Compliance as ComplianceResource;

class ApiComplianceController extends ApiController
{
    /**
     * Get the list of terms and privacy policies.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index(Request $request)
    {
        $terms = Term::orderBy('term_version', 'desc')->paginate($this->getLimitPerPage());

        return ComplianceResource::collection($terms);
    }

    /**
     * Get the detail of a given term.
     *
     * @param Request $request
     *
     * @return ComplianceResource|\Illuminate\Http\JsonResponse
     */
    public function show(Request $request, $termId)
    {
        try {
            $term = Term::where('id', $termId)
                ->firstOrFail();
        } catch (ModelNotFoundException $e) {
            return $this->respondNotFound();
        }

        return new ComplianceResource($term);
    }
}

app/Http/Controllers/Api/Settings/ApiContactFieldTypeController.php
<?php

namespace App\Http\Controllers\Api\Settings;

use Illuminate\Http\Request;
use Illuminate\Database\QueryException;
use App\Models\Contact\ContactFieldType;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Api\ApiController;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Http\Resources\Settings\ContactFieldType\ContactFieldType as ContactFieldTypeResource;

class ApiContactFieldTypeController extends ApiController
{
    /**
     * Get the list of contact field types.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index(Request $request)
    {
        $contactFieldTypes = auth()->user()->account->contactFieldTypes()
                                    ->paginate($this->getLimitPerPage());

        return ContactFieldTypeResource::collection($contactFieldTypes);
    }

    /**
     * Get the detail of a given contact field type.
     *
     * @param Request $request
     *
     * @return ContactFieldTypeResource|\Illuminate\Http\JsonResponse
     */
    public function show(Request $request, $contactFieldTypeId)
    {
        try {
            $contactFieldType = ContactFieldType::where('account_id', auth()->user()->account_id)
                ->where('id', $contactFieldTypeId)
                ->firstOrFail();
        } catch (ModelNotFoundException $e) {
            return $this->respondNotFound();
        }

        return new ContactFieldTypeResource($contactFieldType);
    }

    /**
     * Store the contactfieldtype.
     *
     * @param Request $request
     *
     * @return ContactFieldTypeResource|\Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $isvalid = $this->validateUpdate($request);
        if ($isvalid !== true) {
            return $isvalid;
        }

        try {
            $contactFieldType = ContactFieldType::create(
                $request->except(['account_id'])
                + ['account_id' => auth()->user()->account_id]
            );
        } catch (QueryException $e) {
            return $this->respondNotTheRightParameters();
        }

        return new ContactFieldTypeResource($contactFieldType);
    }

    /**
     * Update the contact field type.
     *
     * @param Request $request
     * @param int $contactFieldTypeId
     *
     * @return ContactFieldTypeResource|\Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $contactFieldTypeId)
    {
        try {
            $contactFieldType = ContactFieldType::where('account_id', auth()->user()->account_id)
                ->where('id', $contactFieldTypeId)
                ->firstOrFail();
        } catch (ModelNotFoundException $e) {
            return $this->respondNotFound();
        }

        $isvalid = $this->validateUpdate($request);
        if ($isvalid !== true) {
            return $isvalid;
        }

        // Update the contactfieldtype itself
        try {
            $contactFieldType->update(
                $request->only([
                    'name',
                    'fontawesome_icon',
                    'protocol',
                    'delible',
                    'type',
                ])
            );
        } catch (QueryException $e) {
            return $this->respondNotTheRightParameters();
        }

        return new ContactFieldTypeResource($contactFieldType);
    }

    /**
     * Validate the request for update.
     *
     * @param  Request $request
     * @return \Illuminate\Http\JsonResponse|true
     */
    private function validateUpdate(Request $request)
    {
        // Validates basic fields to create the entry
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'fontawesome_icon' => 'nullable|max:255',
            'protocol' => 'nullable|max:255',
            'delible' => 'integer',
            'type' => 'nullable|max:255',
        ]);

        if ($validator->fails()) {
            return $this->respondValidatorFailed($validator);
        }

        return true;
    }

    /**
     * Delete an contactfieldtype.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Request $request, $contactFieldTypeId)
    {
        try {
            $contactFieldType = ContactFieldType::where('account_id', auth()->user()->account_id)
                ->where('id', $contactFieldTypeId)
                ->firstOrFail();
        } catch (ModelNotFoundException $e) {
            return $this->respondNotFound();
        }

        $contactFields = auth()->user()->account->contactFields
                                ->where('contact_field_type_id', $contactFieldTypeId);

        foreach ($contactFields as $contactField) {
            $contactField->delete();
        }

        $contactFieldType->delete();

        return $this->respondObjectDeleted($contactFieldType->id);
    }
}

resources/views/settings/export.blade.php
@extends('layouts.skeleton')

@section('content')

<div class="settings">

  {{-- Breadcrumb --}}
  <div class="breadcrumb">
    <div class="{{ Auth::user()->getFluidLayout() }}">
      <div class="row">
        <div class="col-12">
          <ul class="horizontal">
            <li>
              <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
            </li>
            <li>
              <a href="{{ route('settings.index') }}">{{ trans('app.breadcrumb_settings') }}</a>
            </li>
            <li>
              {{ trans('app.breadcrumb_settings_export') }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="{{ Auth::user()->getFluidLayout() }}">
    <div class="row">

      @include('settings._sidebar')

      <div class="col-12 col-sm-9">

        <div class="br3 ba b--gray-monica bg-white mb4">
          <div class="pa3 bb b--gray-monica">
            <h3>{{ trans('settings.export_title') }}</h3>
            <h4>{{ trans('settings.export_title_sql') }}</h4>
            <p>{{ trans('settings.export_sql_explanation') }}</p>
            <p>{{ trans('settings.export_be_patient') }}</p>
            <p><a href="{{ route('settings.sql') }}" class="btn">{{ trans('settings.export_sql_cta') }}</a></p>
            <p>{!! trans('settings.export_sql_link_instructions', ['url' => 'https://github.com/monicahq/monica/blob/master/docs/installation/update.md#importing-sql-from-the-exporter-feature']) !!}</p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

@endsection

resources/views/settings/index.blade.php
@extends('layouts.skeleton')

@section('content')

<div class="settings">

  {{-- Breadcrumb --}}
  <div class="breadcrumb">
    <div class="{{ auth()->user()->getFluidLayout() }}">
      <div class="row">
        <div class="col-12">
          <ul class="horizontal">
            <li>
              <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
            </li>
            <li>
              {{ trans('app.breadcrumb_settings') }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="{{ auth()->user()->getFluidLayout() }} mb4">
    <div class="row">

      @include('settings._sidebar')

      <div class="col-12 col-md-9">
        <div class="br3 ba b--gray-monica bg-white mb4">
          <div class="pa3 bb b--gray-monica">

            @include('partials.errors')

            @if (session('status'))
            <div class="alert alert-success">
              {{ session('status') }}
            </div>
            @endif

            <form action="{{ route('settings.save') }}" method="POST">
              @csrf

              {{-- id --}}
              <input type="hidden" name="id" value="{{ auth()->user()->id }}" />

              <h2>@lang('settings.title_general')</h2>
              <div class="pa2">
                {{-- names --}}
                <div class="form-group">
                  <label for="first_name" class="mb2 b">{{ trans('settings.firstname') }}</label>
                  <input type="text" class="form-control" name="first_name" id="first_name" required value="{{ auth()->user()->first_name }}">
                </div>

                <div class="form-group">
                  <label for="last_name" class="mb2 b">{{ trans('settings.lastname') }}</label>
                  <input type="text" class="form-control" name="last_name" id="last_name" required value="{{ auth()->user()->last_name }}">
                </div>

                {{-- email address --}}
                <div class="form-group">
                  <label for="email" class="mb2 b">{{ trans('settings.email') }}</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="{{ trans('settings.email_placeholder') }}" required value="{{ auth()->user()->email }}">
                  <small id="emailHelp" class="form-text text-muted">{{ trans('settings.email_help') }}</small>
                </div>

                <div class="form-group">
                  <label class="mb2 b">@lang('settings.me_title')</label>
                  <me-contact
                    :existing-contacts="{{ \Safe\json_encode($existingContacts) }}"
                    :contact="{{ \Safe\json_encode($meContact) }}"
                    :limited="{{ \Safe\json_encode($accountHasLimitations) }}"
                  >
                  </me-contact>
                  <small class="form-text text-muted">@lang('settings.me_help')</small>
                </div>
              </div>

              <h2 class="pt3">@lang('settings.title_i18n')</h2>
              <div class="pa2">
                {{-- Locale --}}
                <div class="form-group">
                  <label for="locale" class="mb2 b">{{ trans('settings.locale') }}</label>
                  <select class="form-control" name="locale" id="locale">
                    @foreach($locales as $locale)
                      <option value="{{ $locale['lang'] }}" {{ (auth()->user()->locale === $locale['lang'])?'selected':'' }}>
                        {{ $locale['name-orig'] }}
                        @if (auth()->user()->locale !== $locale['lang'] && $locale['name-orig'] !== $locale['name'])
                          — {{ $locale['name'] }}
                        @endif
                      </option>
                    @endforeach
                  </select>
                  <small class="form-text text-muted">{!! trans('settings.locale_help', ['url' => 'https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md']) !!}</small>
                </div>

                {{-- currency for user --}}
                <div class="form-group">
                  <label for="currency_id" class="mb2 b">{{ trans('settings.currency') }}</label>
                  @include('partials.components.currency-select', ['selectionID' => auth()->user()->currency_id ])
                </div>

                {{-- Temperature scale --}}
                <div class="form-group">
                  <label for="temperature_scale" class="mb2 b">{{ trans('settings.temperature_scale') }}</label>
                  <select class="form-control" name="temperature_scale" id="temperature_scale">
                    <option value="fahrenheit" {{ (auth()->user()->temperature_scale == 'fahrenheit')?'selected':'' }}>{{ trans('settings.temperature_scale_fahrenheit') }}</option>
                    <option value="celsius" {{ (auth()->user()->temperature_scale == 'celsius')?'selected':'' }}>{{ trans('settings.temperature_scale_celsius') }}</option>
                  </select>
                </div>

                {{-- Reminder --}}
                <div class="form-group">
                  <reminder-time
                  :reminder="'{{ auth()->user()->account->default_time_reminder_is_sent }}'"
                  :timezone="'{{ $selectedTimezone }}'"
                  :timezones="{{ \Safe\json_encode($timezones) }}"
                  :hours="{{ \Safe\json_encode($hours) }}">
                  </reminder-time>
                </div>
              </div>

              <h2 class="pt3">@lang('settings.title_layout')</h2>
              <div class="pa2">
                {{-- Way of displaying names --}}
                <div class="form-group">
                  <label for="name_order" class="mb2 b">{{ trans('settings.name_order') }}</label>
                  <select id="name_order" name="name_order" class="form-control">
                    @foreach ($namesOrder as $nameOrder)
                    <option value="{{ $nameOrder }}" {{ (auth()->user()->name_order == $nameOrder) ? 'selected':'' }}>{{ trans('settings.name_order_'.$nameOrder) }}</option>
                    @endforeach
                  </select>
                </div>

                {{-- Layout --}}
                <div class="form-group">
                  <label for="layout" class="mb2 b">{{ trans('settings.layout') }}</label>
                  <select class="form-control" name="layout" id="layout">
                    <option value='false' {{ (auth()->user()->fluid_container == 'false')?'selected':'' }}>{{ trans('settings.layout_small') }}</option>
                    <option value='true' {{ (auth()->user()->fluid_container == 'true')?'selected':'' }}>{{ trans('settings.layout_big') }}</option>
                  </select>
                </div>
              </div>

              <button type="submit" class="btn btn-primary">{{ trans('settings.save') }}</button>
            </form>
          </div>
        </div>

        <form method="POST" action="{{ route('settings.reset') }}" class="settings-reset bg-white" onsubmit="return confirm('{{ trans('settings.reset_notice') }}')">
          @csrf

          <h2>{{ trans('settings.reset_title') }}</h2>
          <p>{{ trans('settings.reset_desc') }}</p>
          <button type="submit" class="btn">{{ trans('settings.reset_cta') }}</button>
        </form>

        <form method="POST" action="{{ route('settings.delete') }}" class="settings-delete bg-white" onsubmit="return confirm('{{ trans('settings.delete_notice') }}')">
          @csrf

          <h2>{{ trans('settings.delete_title') }}</h2>
          <p>{{ trans('settings.delete_desc') }}</p>
          <p>{{ trans('settings.delete_other_desc') }}</p>
          <button type="submit" class="btn">{{ trans('settings.delete_cta') }}</button>
        </form>

      </div>
    </div>
  </div>
</div>

@endsection

resources/views/settings/tags.blade.php
@extends('layouts.skeleton')

@section('content')

<div class="settings">

  {{-- Breadcrumb --}}
  <div class="breadcrumb">
    <div class="{{ Auth::user()->getFluidLayout() }}">
      <div class="row">
        <div class="col-12">
          <ul class="horizontal">
            <li>
              <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
            </li>
            <li>
              <a href="{{ route('settings.index') }}">{{ trans('app.breadcrumb_settings') }}</a>
            </li>
            <li>
              {{ trans('app.breadcrumb_settings_tags') }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="{{ Auth::user()->getFluidLayout() }}">
    <div class="row">

      @include('settings._sidebar')

      <div class="col-12 col-sm-9">
        <div class="br3 ba b--gray-monica bg-white mb4">
          <div class="pa3 bb b--gray-monica">
            @if (auth()->user()->account->tags->count() == 0)

              <div class="col-12 col-sm-9 blank-screen">

              <img src="img/settings/tags/tags.png">

              <h2>{{ trans('settings.tags_blank_title') }}</h2>

              <p>{{ trans('settings.tags_blank_description') }}</p>

            </div>

            @else

              <h3 class="with-actions">
                {{ trans('settings.tags_list_title') }}
              </h3>

              <p>{{ trans('settings.tags_list_description') }}</p>

              @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
              @endif

              <ul class="table">
              @foreach (auth()->user()->account->tags as $tag)
                <li class="table-row" data-tag-id="{{ $tag->id }}">
                  <div class="table-cell">
                    {{ $tag->name }}
                    <span class="tags-list-contact-number">({{ trans_choice('settings.tags_list_contact_number', $tag->contacts()->count(), ['count' => $tag->contacts()->count()]) }})</span>
                    <ul>
                      @foreach($tag->contacts as $contact)
                      <li class="di mr1"><a href="people/{{ $contact->hashID() }}">{{ $contact->name }}</a></li>
                      @endforeach
                    </ul>
                  </div>
                  <div class="table-cell actions">
                    <form method="POST" action="{{ route('settings.tags.delete', $tag) }}">
                      @method('DELETE')
                      @csrf
                      <confirm message="{{ trans('settings.tags_list_delete_confirmation') }}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                      </confirm>
                    </form>
                  </div>

                </li>
              @endforeach
              </ul>

            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection